[package]
name = "cargo-spaced"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/what386/cargo-spaced"
description = ""
keywords = []
categories = []

exclude = [
    ".github",
    "scripts/",
]

[dependencies]
ra_ap_syntax = "0.0.347"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
walkdir = "2.5"
