[package]
name = "cargo-spaced"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/what386/cargo-spaced"
description = "A blankline formatter for Rust source code"
keywords = ["cargo", "formatter", "formatting", "blank-lines"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

exclude = [
    ".github",
    "scripts/",
]

[dependencies]
ra_ap_syntax = "0.0.347"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1"
walkdir = "2.5"
